### ISSUE TITLE
default='null' is treated as string, not as null value

### ISSUE THREAD

**Issue by dragutint** [wiremock/wiremock-state-extension#67]
### Proposal

Improve usage of `default='null'` when setting the value in context, and afterward using it in the response. Treat it like a null value, not the string "null"

### Reproduction steps

I have a recordState event listener and there I'm saving the state of some context. For example:
`{
    "name": "recordState",
    "parameters": {
       "state": {
          "id": "{{jsonPath response.body '$.id'}}",
          "name": "{{jsonPath request.body '$.name'}}",
          "externalId": "{{jsonPath request.body '$.externalId' default='null'}}"
       },
       "context": "resource-{{jsonPath response.body '$.id'}}"
    }
}`

If externalId is not passed, I'm defaulting it to null

When I'm using this state from the context, in some GET endpoint, the value of externalId is set in the response JSON as 'null', like string value, not the null value of a field.

**Comment by dirkbolte** [comment]
currently, a missing property results in an unreadable error being inserted. I was thinking whether changing the default behavior might be a good approach, so:

- if a property does not exist and NO default is specified: return `null` and log an info event (visible with `verbose=true`)
- if a property does not exist and a default is specified

Same would probably apply when the context is missing (have to double check).

Would prefer this approach as it's a little more obvious at least to me and I don't have to add handling for special keywords like `null` .

What do you think?

**Comment by dragutint** [comment]
> currently, a missing property results in an unreadable error being inserted. I was thinking whether changing the default behavior might be a good approach, so:
> 
> * if a property does not exist and NO default is specified: return `null` and log an info event (visible with `verbose=true`)
> * if a property does not exist and a default is specified
> 
> Same would probably apply when the context is missing (have to double check).
> 
> Would prefer this approach as it's a little more obvious at least to me and I don't have to add handling for special keywords like `null` .
> 
> What do you think?

Yes. You're right I think. It seems like a better approach, since 'default' indirectly says that the field is not nullable, and 'null' as a string can also be a value.

**Comment by dirkbolte** [comment]
This won't be too pretty. In order to be able to use `{{state ...}}` with `jsonBody`, it needs to return a String WITHOUT quotation marks, as these are added afterwards. For that reason, when returning `null`, it will be an empty string. 

If we move this to a body file, `null` will be not be rendered, resulting in an invalid JSON. Returning the string `"null"`  won't work either as there's no easy differentiation between this and and actual string, allowing to add or remove quotation marks. 

But it can be made to work using both an adaption + some handlebars logic:

- `{{state ...}}` will return an empty string when a property not found and no default is specified
  - this can safely be used in both `jsonBody` as well as `bodyFile`
- an empty string is evaluated as `false` by handlebars, allowing to build custom logic. So you can explicitly set the value to `null` or remove the whole property:
  - `{ "value": null}` : 
    ```json
       { 
          "value": {{#with (state context='context' property='myProperty') as | value |}}"{{value}}"{{else}}null{{/with}}
       }
    ```
  - removing the property: `{}` : 
    ```json
    { 
        {{#with (state context='context' property='myProperty') as | value |}}
        "value": "{{value}}"
        {{else}}
    }

This is not too usable but I see no other way to achieve it. I will add proper documentation for this.

**Comment by dragutint** [comment]
Yeah, I understand. No matter the way to achieve this, it's possible, so I think it's OK. 😄

**Comment by dirkbolte** [comment]
@dragutint can you check the PR for whether it covers your issue? (and also comment on the code if you like)

**Comment by dirkbolte** [comment]
merged it. As this is breaking I want to add a bit more before releasing 0.3.0 . Any further feedback on this change or anything else is always welcome.

**Comment by dragutint** [comment]
@dirkbolte sorry for the late reply. Checked, covers it. Thanks!
